language: php
php:
  - 7.2
jobs:
  include:
    - stage: release
      deploy:
        provider: script
        email: mihael.lovrencic@wirecard.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        script: bash bin/deploy.sh
