language: php
php:
  - 7.2
jobs:
  include:
    - stage: release
      deploy:
        provider: npm
        email: mihael.lovrencic@wirecard.com
        api_key: ea53abfb-d8a3-488e-9b6f-4125c062b663
        skip_cleanup: true
        after_deploy: bash bin/deploy.sh
